### Simple get by label

GET http://localhost:8080/photos/test

### Upload without an image

POST http://localhost:8080/photo
Content-Type: application/json

{
  "id": "test",
  "label": "ray"
}

### Upload new image

POST http://localhost:8080/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="photo.txt"

< ./images/cat.jpeg
--WebAppBoundary--

###